---

yaml-files:
  - '*.yaml'
  - '*.yml'
  - '.yamllint'


ignore-from-file: .gitignore

rules:
  braces:
    level: error
    max-spaces-inside: 1
  brackets:
    level: error
    max-spaces-inside: 1
  colons:
    level: warning
  commas:
    level: warning
  comments: disable
  comments-indentation: disable
  document-start: disable
  empty-lines:
    level: warning
  hyphens:
    level: warning
  indentation:
    level: error
    indent-sequences: consistent
  line-length:
    level: warning
    allow-non-breakable-inline-mappings: true
  truthy: disable
