name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: [
      release-linux,  
      release-macos, 
      release-windows          
    ]
    steps:
      - name: Download Linux Binary
        uses: actions/download-artifact@v3
        with:
          name: linux-binary
          path: .
      - name: Download macOS Binary
        uses: actions/download-artifact@v3
        with:
          name: macos-binary
          path: .
      - name: Download Windows Binary
        uses: actions/download-artifact@v3
        with:
          name: windows-binary
          path: .
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            SwiftOpenAPICLI-linux
            SwiftOpenAPICLI-linux.sha256
            SwiftOpenAPICLI-macos
            SwiftOpenAPICLI-macos.sha256
            SwiftOpenAPICLI.exe
            SwiftOpenAPICLI-windows.sha256
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
