name: Create Release

permissions:
  contents: read

on:
  push:
    branches:
      main
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  linux:
    if: vars.RUN_LINUX_TESTS == 'true'
    runs-on: ubuntu-latest
    container:
      image: swift:6.0.3-jammy
    needs: [soundness]
    steps:
      - uses: actions/checkout@v4
      - name: Test
        run: swift build && swift test
  soundness:
    name: Soundness
    uses: swiftlang/github-workflows/.github/workflows/soundness.yml@0.0.2
    with:
      license_header_check_project_name: "Swift"
      license_header_check_enabled: false
      unacceptable_language_check_enabled: true
      api_breakage_check_enabled: false
      format_check_enabled: false
      shell_check_enabled: false
  upload-linux:
    needs: [soundness, linux]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Release
        run: |
          swift build -c release --product SwiftOpenAPICLI
          strip .build/release/SwiftOpenAPICLI
          cp .build/release/SwiftOpenAPICLI SwiftOpenAPICLI
          shasum -a 256 SwiftOpenAPICLI > SwiftOpenAPICLI.sha256
      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-cli
          path: |
            SwiftOpenAPICLI
            SwiftOpenAPICLI.sha256
  macos-arm:
    if: vars.RUN_MACOS_TESTS == 'true'
    runs-on: macos-latest
    needs: [soundness]
    steps:
      - uses: actions/checkout@v4
      - name: Test
        run: swift build && swift test
  upload-macos-arm:
    needs: [macos-arm]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Release
        run: |
          swift build -c release --product SwiftOpenAPICLI
          strip .build/release/SwiftOpenAPICLI
          cp .build/release/SwiftOpenAPICLI SwiftOpenAPICLI
          shasum -a 256 SwiftOpenAPICLI > SwiftOpenAPICLI.sha256
      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-arm-cli
          path: |
            SwiftOpenAPICLI
            SwiftOpenAPICLI.sha256
  macos-x86:
    if: vars.RUN_MACOS_TESTS == 'true'
    runs-on: macos-15-intel
    needs: [soundness]
    steps:
      - uses: actions/checkout@v4
      - name: Test
        run: swift build && swift test
  upload-macos-x86:
    needs: [soundness, macos-x86]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Release
        run: |
          swift build -c release --product SwiftOpenAPICLI
          strip .build/release/SwiftOpenAPICLI
          cp .build/release/SwiftOpenAPICLI SwiftOpenAPICLI
          shasum -a 256 SwiftOpenAPICLI > SwiftOpenAPICLI.sha256
      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-x86_64-cli
          path: |
            SwiftOpenAPICLI
            SwiftOpenAPICLI.sha256
  windows:
    if: vars.RUN_WINDOWS_TESTS == 'true'
    runs-on: windows-latest
    needs: [soundness]
    steps:
      - uses: actions/checkout@v4
      - name: Install Swift on Windows
        uses: compnerd/swift-build@v0.1
        with:
          platform: windows
      - name: Build .exe
        run: |
          swift build -c release --product SwiftOpenAPICLI
          shasum -a 256 .build\release\SwiftOpenAPICLI.exe > SwiftOpenAPICLI.sha256

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-cli
          path: |
            .build\release\SwiftOpenAPICLI.exe
            SwiftOpenAPICLI.sha256
  release:
    needs: [upload-macos-x86, upload-macos-arm, windows, upload-linux]
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            artifacts/macos-x86_64-cli/SwiftOpenAPICLI.exe
            artifacts/macos-x86_64-cli/SwiftOpenAPICLI.sha256
            artifacts/linux-cli/SwiftOpenAPICLI
            artifacts/linux-cli/SwiftOpenAPICLI.sha256
            artifacts/windows-cli/SwiftOpenAPICLI
            artifacts/windows-cli/SwiftOpenAPICLI.sha256
            artifacts/macos-arm-cli/SwiftOpenAPICLI
            artifacts/macos-arm-cli/SwiftOpenAPICLI.sha256
